services:
  - type: web
    name: baicai-s5-auction
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/meta
    envVars:
      - key: AUCTION_JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.0"
